name: test_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  intl_phone_number_input: ^0.7.1
  sqflite: ^2.1.0+1
  http: ^0.13.5
  get: 4.6.5
  flutter_contacts: ^1.1.5
  url_launcher: ^6.1.6
  flutter_svg: ^1.1.5
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.6
  local_auth: ^2.1.2
  lottie: ^1.4.3
  email_auth: ^1.0.0
  flutter_animate: ^1.0.0
  flutter_animated_button: ^2.0.1
  persistent_bottom_nav_bar: ^5.0.2
  flutter: 
    sdk: flutter
  shared_preferences: ^2.0.15
  inner_shadow_widget: ^0.0.3
  intl_phone_field: ^3.1.0
  side_sheet: ^1.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/animations/

